[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[build.args]
DOCKER_BUILDKIT = "1"

[build.steps]
[build.steps.docker-build]
command = "docker build --progress=plain --network=host -t app ."

